build:
  version: "1.0"

productservice:
  message: "Welcome to Ecommerce Product Service related webhoook APIs"
  contactDetails:
    name: "Mostafa - Developer"
    email: "productlocal@ecommerce.com"
  onCallSupport:
    - (+20) 01555331990
